# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:MYSQL_USER:root"
  password: "_env:MYSQL_PASSWORD:r00t"
  host:     "_env:MYSQL_HOST:localhost"
  port:     "_env:MYSQL_PORT:5432"
  database: "_env:MYSQL_DATABASE:aws-photo-service"
  poolsize: "_env:MYSQL_POOLSIZE:10"

metadata:
  name:         "File:FileName"
  src:          "SourceFile"
  width:        "File:ImageWidth"
  height:       "File:ImageHeight"
  author:       "EXIF:Artist"
  caption:      "IPTC:Caption-Abstract"
  date:         "EXIF:CreateDate"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE
